<?php

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit();
}

webchanges_connector_register_ability('image-generate', [
    'label' => __('Generate Image (AI)', 'webchanges-connector'),
    'description' => __(
        'Generate one or more images from a text prompt using the configured AI provider (OpenAI, Google Gemini, or Replicate). Images are uploaded to the media library with alt text set. Defaults pull from the saved settings; pass `provider`, `model`, or `size` to override per call.',
        'webchanges-connector'
    ),
    'category' => 'webchanges-image-gen',
    'input_schema' => [
        'type' => 'object',
        'properties' => [
            'prompt' => ['type' => 'string', 'description' => 'Text description of the image to generate.'],
            'alt' => ['type' => 'string', 'description' => 'Alt text for the resulting attachment. Defaults to a truncation of the prompt.'],
            'provider' => ['type' => 'string', 'enum' => ['openai', 'gemini', 'replicate', 'pollinations']],
            'model' => ['type' => 'string'],
            'size' => ['type' => 'string', 'description' => 'WxH e.g. "1024x1024", "1792x1024" (landscape), "1024x1792" (portrait), or "auto".'],
            'count' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 4, 'description' => 'Number of variations to generate.'],
            'parent_post_id' => ['type' => 'integer', 'description' => 'Optional post id to attach the resulting media to.'],
            'filename_base' => ['type' => 'string', 'description' => 'Filename stem (without extension). Defaults to a slugified prompt.'],
            'upload_to_library' => ['type' => 'boolean', 'description' => 'When false (default true) the response carries base64 bytes and skips media insertion.'],
        ],
        'required' => ['prompt'],
        'additionalProperties' => false,
    ],
    'output_schema' => [
        'type' => 'object',
        'properties' => [
            'provider' => ['type' => 'string'],
            'model' => ['type' => 'string'],
            'attachment_ids' => ['type' => 'array', 'items' => ['type' => 'integer']],
            'attachment_urls' => ['type' => 'array', 'items' => ['type' => 'string']],
            'images' => ['type' => 'array', 'description' => 'When upload_to_library=false: base64 bytes per image.'],
        ],
    ],
    'execute_callback' => static function (array $input): array {
        $prompt = trim((string) ($input['prompt'] ?? ''));
        if ($prompt === '') {
            return ['success' => false, 'error' => 'prompt is required'];
        }
        $alt = trim((string) ($input['alt'] ?? ''));
        if ($alt === '') {
            $alt = mb_substr($prompt, 0, 120);
        }
        $count = max(1, min(4, (int) ($input['count'] ?? 1)));
        $parent_post_id = (int) ($input['parent_post_id'] ?? 0);
        $upload = (bool) ($input['upload_to_library'] ?? true);

        $result = webchanges_image_gen_generate($prompt, [
            'provider' => isset($input['provider']) ? (string) $input['provider'] : '',
            'model' => isset($input['model']) ? (string) $input['model'] : '',
            'size' => isset($input['size']) ? (string) $input['size'] : '',
            'count' => $count,
        ]);
        if (is_wp_error($result)) {
            return ['success' => false, 'error' => $result->get_error_message()];
        }

        if (!$upload) {
            return [
                'provider' => $result['provider'],
                'model' => $result['model'],
                'attachment_ids' => [],
                'attachment_urls' => [],
                'images' => $result['images'],
            ];
        }

        $base = isset($input['filename_base']) && is_string($input['filename_base']) && $input['filename_base'] !== ''
            ? sanitize_title((string) $input['filename_base'])
            : sanitize_title(mb_substr($prompt, 0, 60));
        if ($base === '') {
            $base = 'ai-image-' . time();
        }

        $provenance = sprintf("Generated by Webchanges Connector\nProvider: %s\nModel: %s\nPrompt: %s", $result['provider'], $result['model'], $prompt);

        $ids = [];
        $urls = [];
        foreach ($result['images'] as $i => $img) {
            $name = $count === 1 ? $base : $base . '-' . ($i + 1);
            $up = webchanges_image_gen_to_media(
                (string) $img['b64'],
                (string) $img['mime_type'],
                $name,
                $alt,
                $parent_post_id,
                $provenance
            );
            if (!empty($up['success'])) {
                $ids[] = (int) $up['attachment_id'];
                $urls[] = (string) $up['url'];
            }
        }

        return [
            'provider' => $result['provider'],
            'model' => $result['model'],
            'attachment_ids' => $ids,
            'attachment_urls' => $urls,
        ];
    },
    'meta' => [
        'annotations' => [
            'readonly' => false,
            'destructive' => true,
            'idempotent' => false,
        ],
    ],
]);
